#!/bin/sh

set -x

if [ "$CRTOOLS_SCRIPT_ACTION" != "setup-namespaces" ] ; then
  exit 0
fi

[ ! -d "$MINC_TMPDIR" ] && exit 1

. $MINC_TMPDIR/settings

export MINC_SETUPONLY=yes

/usr/local/libexec/minc-core
