#!/bin/sh
#  marten : Manager of image archives and temporary-containers 

set -e -u
MINC=`dirname $0`/minc
LIBEXEC=`dirname $0`/libexec
MINCFARM=$LIBEXEC/minc-farm

usage() { # [error messages]
  test $# -ne 0 && echo "$*"
  echo "$0 - Manager of image archives and temporary-containers"
  echo "Usage: $0 [action] <command> [argument...]"
  echo " commands:"
  echo "    lc or list          List containers"
  echo "    li or images        List images"
  echo "    rm UUID             Remove specified container"
  echo "    rmi UUID            Remove specified image"
  echo "    import DIR|IMAGE    Import DIR or Dokcer IMAGE as an image"
  echo "    commit UUID         Commit specified container to image"
  echo " options:"
  echo "    -h or --help        Show this help"
  echo "    --long              Show long ID with li/lc commands"

  exit $#
}

do_list() { # command [opts..]
  cmd=$1
  shift 1
  export MINC_LONG_ID=
  while [ $# -ne 0 ]; do
    case $1 in
      --long|-l)
      export MINC_LONG_ID=1
      ;;
    esac
    shift 1
  done
  $MINCFARM $cmd
}

import_docker() {
  FILE=$1
  OPT=
  case $FILE in
  *tar.gz) OPT="-z" ;;
  *tar.bz) OPT="-j" ;;
  esac
  NAME=`tar $OPT -xf $FILE repositories -O | jq -r "keys[0]" `
  IMAGE=`tar $OPT -xf $FILE repositories -O | jq -r ".[] | .[]" `
  if [ -z "$NAME" -o -z "$IMAGE" ]; then
    usage "$FILE is not a docker image"
  fi
  echo "Importing image: $NAME"

  IDS=
  ID=$IMAGE
  while [ "$ID" -a "$ID" != "null" ]; do
    IDS="$ID $IDS"
    ID=`tar $OPT -xf $FILE $ID/json -O | jq -r ".parent"`
  done
  for id in $IDS; do
    tmproot=`mktemp -d`
    tar $OPT -xf $FILE $id/layer.tar -O | tar -x -C $tmproot
    export MINC_IMPORT_UUID=$id
    if [ $id = $IMAGE ]; then
      export MINC_IMPORT_NAME=$NAME
    fi
    $MINCFARM import $tmproot
    export MINC_BASE_UUID=$id
    rm -rf $tmproot
  done
  exit 0
}


test $# -eq 0 && usage
cmd=$1
shift 1
case $cmd in
  lc|list|li|images)
  do_list $cmd $*
  ;;
  import)
  test -d $1 || import_docker $1
  $MINCFARM import $1
  ;;
  commit)
  $MINCFARM commit $1
  ;;
  rm)
  $MINCFARM rm $1
  ;;
  rmi)
  $MINCFARM rmi $1
  ;;
  *)
  usage
esac

