#!/bin/sh
# minc : Pure shell script mini container command
#
# Copyright (C) 2014,2015 Masami Hiramatsu <masami.hiramatsu@gmail.com>
# This program is released under the MIT License, see LICENSE.
#
# This requires util-linux newer than 2.24 (unshare "-f"
# option and mount correctly support /proc/mounts)

LIBEXEC=`dirname $0`/libexec
MINCEXEC=$LIBEXEC/minc-exec
MINCCOAT=$LIBEXEC/minc-coat
MINCFARM=$LIBEXEC/minc-farm

# Exit if any errors
set -e
set -u

usage() { # [error messages]
  test $# -ne 0 && echo "$*"
  echo "$0 - Run given command in a temporary namespace"
  echo "Usage: $0 [options] <command> [argument...]"
  echo " options:"
  echo "    -h or --help        Show this help"
  echo "    -k or --keep        Keep the temporary directory"
  echo "    -t or --tempdir <DIR>  Set DIR for temporary directory (imply -k)"
  echo "                    <UUID> Reuse UUID named container"
  echo "    -r or --rootdir <DIR>  Set DIR for original root directory"
  echo "                    <UUID> Use UUID named container image"
  echo "    -X or --X11         Export local X11 unix socket"
  echo "    -n or --net         Use network namespace"
  echo "    -c or --cpu <mask>  Set CPU mask"
  echo "    -p or --pty         Assign new pty for the container"
  echo "    --name <NAME>       Set <NAME> as container's name (hostname)"
  echo "    --user <USER>[:GROUP]  specify user and group (ID or name) to use"
  echo "    --simple            Simple chroot model (do not pivot_root)"
  echo "    --usedev		Use devtmpfs for /dev (for loopback etc.)"
  echo "    --debug             Debug mode"
  exit $#
}

KEEPDIR=0
USE_FARM=
MINC_TMPDIR=
export MINC_DEBUG_PREFIX=
export MINC_RWBIND=
export MINC_OPT_SIMPLE=
export MINC_OPT_PTY=
export MINC_CPUMASK=
export MINC_NETNS=
export MINC_DEBUG=
export MINC_BASEDIR=/
export MINC_USE_DEV=
export MINC_UTSNAME=
# Parse options
while [ "$#" -ne 0 ]; do
case "$1" in
  --keep|-k) # Keep the temporary directory
    KEEPDIR=1
    shift 1
    ;;
  --tempdir|-t) # Give a temporary directory (imply -k)
    export MINC_TMPDIR=$2
    KEEPDIR=1
    if [ ! -d "$2" ]; then
      USE_FARM=container
    fi
    shift 2
    ;;
  --rootdir|-r) # Give a rootdir or image instead of /
    export MINC_BASEDIR=$2
    if [ ! -d "$2" ]; then
      $MINCFARM pull $2	# ensure the given id image exists
      USE_FARM=image
    fi
    shift 2
    ;;
  --X11|-X) # Export X11 connection
    [ -z "$DISPLAY" ] && usage "Error: \$DISPLAY is empty"
    export MINC_RWBIND="/tmp/.X11-unix"
    shift 1
    ;;
  --net|-n) # Use NetNS
    export MINC_NETNS="minc$$"
    shift 1
    ;;
  --cpu|-c) # Use CPU mask
    MINC_CPUMASK=$2
    shift 2
    ;;
  --simple) # Simple chroot model (do not pivot_root and umount)
    export MINC_OPT_SIMPLE=1
    shift 1
    ;;
  --pty|-p)
    export MINC_OPT_PTY=1
    shift 1
    ;;
  --name)
    export MINC_UTSNAME=$2
    shift 2
    ;;
  --user)
    export MINC_USERSPEC=$2
    shift 2
    ;;
  --usedev)
    export MINC_USE_DEV=1
    shift 1
    ;;
  --help|-h) # Help Message
    usage
    ;;
  --debug) # Debug mode
    set -x
    export MINC_DEBUG=1
    shift 1
    ;;
  [!-]*) # User given command
    break
    ;;
  *)
    usage "Parse error: $1 is not supported."
    ;;
esac
done

TRAPCMD=
if [ -z "$USE_FARM" ]; then
  # Setup temporary directory
  if [ -z "$MINC_TMPDIR" ]; then
    export MINC_TMPDIR=`mktemp -d /tmp/minc$$-XXXXXX`
  fi
  if [ $KEEPDIR -eq 0 ]; then
    TRAPCMD="rm -rf $MINC_TMPDIR"
  else
    TRAPCMD="echo Keep $MINC_TMPDIR"
  fi
  trap "$TRAPCMD" EXIT
elif [ "$USE_FARM" = "image" ]; then
  # Use minc-farm to setup new container
  UUID=`$MINCFARM fork $MINC_BASEDIR`
  export MINC_BASEDIR=`$MINCFARM imagestack $MINC_BASEDIR`
  export MINC_TMPDIR=`$MINCFARM dir $UUID`
else
  # Use minc-farm container
  UUID=`$MINCFARM baseid $MINC_TMPDIR`
  export MINC_BASEDIR=`$MINCFARM imagestack $UUID`
  export MINC_TMPDIR=`$MINCFARM dir $MINC_TMPDIR`
fi

# Setup Network Namespace
if [ "$MINC_NETNS" ]; then
  ip netns add $MINC_NETNS
  TRAPCMD="ip netns del $MINC_NETNS;$TRAPCMD"
  trap "$TRAPCMD" EXIT
  export MINC_NETNSIF=vminc$$
  ip link add name $MINC_NETNSIF type veth peer name veth$$
  ip link set $MINC_NETNSIF netns $MINC_NETNS
fi

trap '' INT
$MINCEXEC $@
