#!/bin/sh
# polecat: Portable Containered Application build shell script
#
# Copyright (C) 2015 Masami Hiramatsu <masami.hiramatsu@gmail.com>
# This program is released under the MIT License, see LICENSE.

LIBEXEC=`dirname $0`/libexec
MINCEXEC=$LIBEXEC/minc-exec
OUTFILE=polecat-out.sh

# Exit if any errors
set -e

usage() { # [error messages]
  test $# -ne 0 && echo "$*"
  echo "$0 - Build a self-executable containered application"
  echo "Usage: $0 [options] <rootdir> <command>"
  echo " options:"
  echo "    -h or --help           Show this help"
  echo "    -o or --output <FILE>  Output to FILE ($OUTFILE)"
  exit $#
}

while [ "$1" ]; do
case $1 in
-h|--help)
  usage
  ;;
-o|--output)
  OUTFILE=$2
  shift 2
  ;;
*)
  break;
  ;;
esac
done

test -d "$1" || usage "$1 is not a directory"
ROOTFS=$1
shift 1

MINC_TMPDIR=`mktemp -d polecat-XXXXXXXX`
trap "rm -rf $MINC_TMPDIR" EXIT

# Working sub-directories
RD=$MINC_TMPDIR/root
UD=$MINC_TMPDIR/storage
WD=$MINC_TMPDIR/work
mkdir -p $RD $UD $WD
# This is for upstreamed overlayfs
mount -t overlay -o upperdir=$UD,lowerdir=$ROOTFS,workdir=$WD overlayfs $RD 2>/dev/null || \
  # Workaround for ubuntu 14.10 (out-of-tree overlayfs)
  mount -t overlayfs -o upperdir=$UD,lowerdir=$ROOTFS overlayfs $RD
trap "umount $RD; rm -rf $MINC_TMPDIR" EXIT

mkdir -p $RD/usr/libexec
install -m 755 $MINCEXEC $RD/usr/libexec/

# Make a squashfs image
SFS=$MINC_TMPDIR/rootfs.sfs
mksquashfs $RD $SFS

SIZE=`stat --format=%s $SFS`
cat > $TMP/polecat.sh << EOF
#!/bin/sh
set -e
SELF=\$0
SIZE=$SIZE
TOTAL=\`stat --format=%s \$SELF\`
OFFS=\$((TOTAL - SIZE))
export PLCDIR=\`mktemp -d polecat-run-XXXXXXXX\`
trap "rm -rf \$PLCDIR" EXIT
export MINC_ROOTDIR=\$PLCDIR/rootfs
export MINC_TMPDIR=\$PLCDIR/tmp
export MINC_OPT_SIMPLE=1
mkdir \$MINC_ROOTDIR \$MINC_TMPDIR
mount -t squashfs -o ro,loop,offset=\$OFFS \$SELF \$MINC_ROOTDIR
trap "umount \$MINC_ROOTDIR; rm -rf \$PLCDIR" EXIT
trap '' INT
sh \$MINC_ROOTDIR/usr/libexec/minc-exec $@
exit \$?
EOF

cat $TMP/polecat.sh $SFS >> $OUTFILE
chmod a+x $OUTFILE

exit 0
