#!/bin/sh
# minc-coat: MINC-container overlay attendant
#
# Copyright (C) 2015 Masami Hiramatsu <masami.hiramatsu@gmail.com>
# This program is released under the MIT License, see LICENSE.

set -e
set -u

# usage: minc-coat bind TMPDIR BASEDIR
#        minc-coat unbind TMPDIR
CMD=$1
TMPDIR=$2

if [ $CMD = bind ]; then
BASEDIR=$3
# Check parameters
test -d $TMPDIR
test -d $BASEDIR

RD=$TMPDIR/root
UD=$TMPDIR/storage
WD=$TMPDIR/work
# Make working sub-directories
mkdir -p $RD $UD $WD

mountpoint $RD > /dev/null || \
# Prepare overlayed root directory
# This is for upstreamed overlayfs
mount -t overlay -o upperdir=$UD,lowerdir=$BASEDIR,workdir=$WD overlayfs $RD 2>/dev/null || \
  # Workaround for ubuntu 14.10 (out-of-tree overlayfs)
  mount -t overlayfs -o upperdir=$UD,lowerdir=$BASEDIR overlayfs $RD

elif [ $CMD = unbind ]; then
  test -d $TMPDIR/root
  mountpoint $TMPDIR/root > /dev/null && umount $TMPDIR/root || echo -n ""
fi
