#!/bin/sh
# minc-coat: MINC-container overlay attendant
#
# Copyright (C) 2015 Masami Hiramatsu <masami.hiramatsu@gmail.com>
# This program is released under the MIT License, see LICENSE.

set -e
set -u

# Check parameters
test -d $MINC_TMPDIR
test -d $MINC_BASEDIR

mkdir -p $MINC_TMPDIR/storage
mkdir -p $MINC_TMPDIR/root

RD=$MINC_TMPDIR/root
UD=$MINC_TMPDIR/storage
WD=$MINC_TMPDIR/work
# Make working sub-directories
mkdir -p $RD $UD $WD

# Prepare overlayed root directory
# This is for upstreamed overlayfs
mount -t overlay -o upperdir=$UD,lowerdir=$MINC_BASEDIR,workdir=$WD overlayfs $RD 2>/dev/null || \
  # Workaround for ubuntu 14.10 (out-of-tree overlayfs)
  mount -t overlayfs -o upperdir=$UD,lowerdir=$MINC_BASEDIR overlayfs $RD

