#!/bin/sh
# minc-leash: MINC least capability shell
#
# Copyright (C) 2015 Masami Hiramatsu <masami.hiramatsu@gmail.com>
# This program is released under the MIT License, see LICENSE.

set -e
test "$MINC_DEBUG" && set -x

minc_wash() {
for i in `env | grep "^MINC_" | cut -f 1 -d=`; do
  unset $i
done
exec $*
}

leash() {
RD=$1
shift 1
if [ "$MINC_DROPCAPS" ]; then
  cmd="-c $@"
  [ x"$cmd" = "x-c " ] && cmd=""
  if [ "$MINC_USERSPEC" ]; then
    OPT=`echo $MINC_USERSPEC | \
    awk 'BEGIN{FS=":"} {if (NF==2) print "--gid="$2; print "--uid="$1}'`
  fi
  minc_wash $MINC_DEBUG_PREFIX capsh --chroot=$RD --drop="$MINC_DROPCAPS" $OPT -- $cmd
else
  test "$MINC_USERSPEC" && OPT="--userspec $MINC_USERSPEC"
  minc_wash $MINC_DEBUG_PREFIX chroot $OPT $RD $@
fi
}

if [ `basename $0` = "minc-leash" ]; then
  leash $@
fi
